services:
  - type: web
    name: banking-backend
    env: node
    plan: free
    buildCommand: cd backend/src && npm install
    startCommand: cd backend/src && node server.js
    envVars:
      - key: NODE_ENV
        value: production